"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Teams = void 0;
const Teams = new Map();
exports.Teams = Teams;
//value in this map represents the team_id MLB designated to each team. 
Teams.set("angels", 108);
Teams.set("diamondbacks", 109);
Teams.set("orioles", 110);
Teams.set("red sox", 111);
Teams.set("cubs", 112);
Teams.set("reds", 113);
Teams.set("guardians", 114);
Teams.set("rockies", 115);
Teams.set("tigers", 116);
Teams.set("astros", 117);
Teams.set("royals", 118);
Teams.set("dodgers", 119);
Teams.set("nationals", 120);
Teams.set("mets", 121);
Teams.set("athletics", 133);
Teams.set("pirates", 134);
Teams.set("padres", 135);
Teams.set("mariners", 136);
Teams.set("giants", 137);
Teams.set("cardinals", 138);
Teams.set("rays", 139);
Teams.set("rangers", 140);
Teams.set("blue jays", 141);
Teams.set("twins", 142);
Teams.set("phillies", 143);
Teams.set("braves", 144);
Teams.set("white sox", 145);
Teams.set("marlins", 146);
Teams.set("yankees", 147);
Teams.set("brewers", 158);
